"""Social simulation relationship types.

Extends the base RelationType with social simulation specific types:
- Agent-memory relationships
- Agent-agent relationships
- Agent-world relationships
- Seed extraction relationships
- Simulation-session relationships
"""

from enum import StrEnum


class SocialRelationType(StrEnum):
    """Relationship types specific to social simulation.

    Categories:
    1. Agent-Memory: How agents relate to memories
    2. Agent-Agent: Social relationships between agents
    3. Agent-World: How agents exist in worlds
    4. Seed-Extraction: Tracing extraction origins
    5. Session-Management: Simulation session tracking
    """

    # Agent-Memory relationships
    HAS_MEMORY = "HAS_MEMORY"  # Agent possesses this memory
    MEMORY_ORIGIN = "MEMORY_ORIGIN"  # Memory originated from this agent
    SHARED_MEMORY = "SHARED_MEMORY"  # Memory shared between agents

    # Agent-Agent social relationships
    KNOWS = "KNOWS"  # Agents know each other
    FRIENDS_WITH = "FRIENDS_WITH"  # Friendship relationship
    FOLLOWS = "FOLLOWS"  # One-way following (social media)
    TRUSTS = "TRUSTS"  # Trust relationship
    INFLUENCES = "INFLUENCES"  # One agent influences another
    CONFLICTS_WITH = "CONFLICTS_WITH"  # Conflict/tension
    FAMILY_OF = "FAMILY_OF"  # Family relationship
    COLLEAGUE_OF = "COLLEAGUE_OF"  # Work relationship

    # Agent-World relationships
    EXISTS_IN = "EXISTS_IN"  # Agent exists in a world
    INTERACTS_IN = "INTERACTS_IN"  # Agent actively interacting in world
    OWNS = "OWNS"  # Agent owns/controls world element

    # Seed-Extraction relationships
    EXTRACTED_FROM = "EXTRACTED_FROM"  # Entity/agent extracted from seed
    GENERATED_BY = "GENERATED_BY"  # Agent generated by seed
    SOURCED_FROM = "SOURCED_FROM"  # General source relationship

    # Session-Management relationships
    PART_OF_SESSION = "PART_OF_SESSION"  # Entity belongs to session
    SESSION_CONTAINS = "SESSION_CONTAINS"  # Session contains entity
    WORLD_OF_SESSION = "WORLD_OF_SESSION"  # World state belongs to session
